### PR TITLE
Option to show more/less message

### LINKED ISSUE #7: Show tooltip message next to arrow
Would be nice to always show the tool tip message as it's not obvious you need to long press to show it.

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
Fixes #7

### CODE REVIEW

**Comment by jesusrp98** [comment]
I'm going to implement some new features and improvements to this package this next few days, because it was something I was planning to do.

In the mean while, I'm going to think how this feature could be implemented, since I think there's a better way to do this. It has to be done right.

Thank for this and all the other contributions @JamesMcIntosh!!

**Comment by JamesMcIntosh** [comment]
Depends on how far you want to go to separate the two widgets.

If you keep the expansion widget inside of the `ExpandText` widget then using a `Builder` to construct the widget would work well.

If you really want to separate them you could as far as pushing the expanded state up the widget tree such as `Provider`.

**Comment by jesusrp98** [comment]
I really like the idea of implementing such thing. But I want to do it right:
- For example, the ability to select where should the text be added: at the left or the right of the arrow.
- Implement a consistent theme for the label, since now is kinda rough.

If you want to and have the time to improve this feature, I'll be more than happy to help you.
This is a good start :)

**Comment by jesusrp98** [comment]
This PR is no longer neccesarry, since another implementation have been performed in the next version. 

Thank you very much @JamesMcIntosh !
Read #7 for more details :)

**Pull request closed without merging**
